JavaJSf/WebApplication18/src/java/jclasses/KupciController.java
package jclasses;

import entites.Kupci;
import jclasses.util.JsfUtil;
import jclasses.util.PaginationHelper;
import bean.KupciFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("kupciController")
@SessionScoped
public class KupciController implements Serializable {

    private Kupci current;
    private DataModel items = null;
    @EJB
    private bean.KupciFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public KupciController() {
    }

    public Kupci getSelected() {
        if (current == null) {
            current = new Kupci();
            selectedItemIndex = -1;
        }
        return current;
    }

    private KupciFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Kupci) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Kupci();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("KupciCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Kupci) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("KupciUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Kupci) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("KupciDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Kupci getKupci(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Kupci.class)
    public static class KupciControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            KupciController controller = (KupciController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "kupciController");
            return controller.getKupci(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Kupci) {
                Kupci o = (Kupci) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Kupci.class.getName());
            }
        }

    }

}

JavaJSf/WebApplication18/web/kupci/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateKupciTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateKupciLabel_id}" for="id" />
                    <h:inputText id="id" value="#{kupciController.selected.id}" title="#{bundle.CreateKupciTitle_id}" required="true" requiredMessage="#{bundle.CreateKupciRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.CreateKupciLabel_ime}" for="ime" />
                    <h:inputText id="ime" value="#{kupciController.selected.ime}" title="#{bundle.CreateKupciTitle_ime}" required="true" requiredMessage="#{bundle.CreateKupciRequiredMessage_ime}"/>
                    <h:outputLabel value="#{bundle.CreateKupciLabel_prezime}" for="prezime" />
                    <h:inputText id="prezime" value="#{kupciController.selected.prezime}" title="#{bundle.CreateKupciTitle_prezime}" required="true" requiredMessage="#{bundle.CreateKupciRequiredMessage_prezime}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{kupciController.create}" value="#{bundle.CreateKupciSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{kupciController.prepareList}" value="#{bundle.CreateKupciShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateKupciIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

JavaJSf/WebApplication18/web/kupci/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditKupciTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditKupciLabel_id}" for="id" />
                    <h:inputText id="id" value="#{kupciController.selected.id}" title="#{bundle.EditKupciTitle_id}" required="true" requiredMessage="#{bundle.EditKupciRequiredMessage_id}"/>
                    <h:outputLabel value="#{bundle.EditKupciLabel_ime}" for="ime" />
                    <h:inputText id="ime" value="#{kupciController.selected.ime}" title="#{bundle.EditKupciTitle_ime}" required="true" requiredMessage="#{bundle.EditKupciRequiredMessage_ime}"/>
                    <h:outputLabel value="#{bundle.EditKupciLabel_prezime}" for="prezime" />
                    <h:inputText id="prezime" value="#{kupciController.selected.prezime}" title="#{bundle.EditKupciTitle_prezime}" required="true" requiredMessage="#{bundle.EditKupciRequiredMessage_prezime}"/>
                </h:panelGrid>
                <h:commandLink action="#{kupciController.update}" value="#{bundle.EditKupciSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditKupciViewLink}"/>
                <br />
                <h:commandLink action="#{kupciController.prepareList}" value="#{bundle.EditKupciShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditKupciIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

JavaJSf/WebApplication18/web/kupci/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListKupciTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListKupciEmpty}" rendered="#{kupciController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{kupciController.items.rowCount > 0}">
                    <h:outputText value="#{kupciController.pagination.pageFirstItem + 1}..#{kupciController.pagination.pageLastItem + 1}/#{kupciController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{kupciController.previous}" value="#{bundle.Previous} #{kupciController.pagination.pageSize}" rendered="#{kupciController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{kupciController.next}" value="#{bundle.Next} #{kupciController.pagination.pageSize}" rendered="#{kupciController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{kupciController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListKupciTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListKupciTitle_ime}"/>
                            </f:facet>
                            <h:outputText value="#{item.ime}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListKupciTitle_prezime}"/>
                            </f:facet>
                            <h:outputText value="#{item.prezime}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{kupciController.prepareView}" value="#{bundle.ListKupciViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{kupciController.prepareEdit}" value="#{bundle.ListKupciEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{kupciController.destroy}" value="#{bundle.ListKupciDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{kupciController.prepareCreate}" value="#{bundle.ListKupciCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListKupciIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

JavaJSf/WebApplication18/web/kupci/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewKupciTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewKupciLabel_id}"/>
                    <h:outputText value="#{kupciController.selected.id}" title="#{bundle.ViewKupciTitle_id}"/>
                    <h:outputText value="#{bundle.ViewKupciLabel_ime}"/>
                    <h:outputText value="#{kupciController.selected.ime}" title="#{bundle.ViewKupciTitle_ime}"/>
                    <h:outputText value="#{bundle.ViewKupciLabel_prezime}"/>
                    <h:outputText value="#{kupciController.selected.prezime}" title="#{bundle.ViewKupciTitle_prezime}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{kupciController.destroyAndView}" value="#{bundle.ViewKupciDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewKupciEditLink}"/>
                <br />
                <h:commandLink action="#{kupciController.prepareCreate}" value="#{bundle.ViewKupciCreateLink}" />
                <br />
                <h:commandLink action="#{kupciController.prepareList}" value="#{bundle.ViewKupciShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewKupciIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>